name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # This triggers the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to DockerHub (optional if you want to push the image to DockerHub)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t mohsin6/go-server-app:latest .
          docker push mohsin6/go-server-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 5: Deploy to Azure VM
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          port: 22
          script: |
            docker pull mohsin6/go-server-app:latest
            docker stop go-server-app || true
            docker rm go-server-app || true
            docker run -d --name go-server-app -p 80:8080 mohsin6/go-server-app:latest
